apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: monitoring-prometheus
  namespace: argocd
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  source:
    repoURL: https://prometheus-community.github.io/helm-charts
    chart: prometheus
    targetRevision: 27.30.0
    helm:
      values: |
        # --- turn off components Autopilot would block ---
        alertmanager: # just don't want
          enabled: false
        kube-state-metrics:
          enabled: false
        nodeExporter:
          enabled: false
        pushgateway:
          enabled: false
        prometheus-node-exporter:
          enabled: false


        # --- Prometheus server settings ---
        server:
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
              ephemeral-storage: 1Gi
            limits:
              cpu: 1
              memory: 2Gi
              ephemeral-storage: 1Gi

          # Keep data ephemeral (no PVC)
          persistentVolume:
            enabled: false
            size: 8Gi

          # Service as ClusterIP
          service:
            type: ClusterIP
            port: 80

          # Scrape only  PEM service (static config; no operator needed)
          scrape_configs:
            - job_name: pem
              kubernetes_sd_configs:
                - role: endpoints
              relabel_configs:
                - source_labels: [__meta_kubernetes_namespace]
                  action: keep
                  regex: pem-dev
                - source_labels: [__meta_kubernetes_service_name]
                  action: keep
                  regex: public-endpoint-monitor-metrics
                - source_labels: [__meta_kubernetes_endpoint_port_name]
                  action: keep
                  regex: metrics


  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
