apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: pem-all-envs
  namespace: argocd
spec:
  generators:
    - list:
        elements:
          - env: dev
            ns: pem-dev
          - env: prod
            ns: pem-prod

  template:
    metadata:
      name: pem-{{env}}
      labels:
        app.kubernetes.io/managed-by: argocd-appset

    spec:
      project: default
      sources:
        - repoURL: oci://europe-west2-docker.pkg.dev/public-endpoint-monitor/public-endpoint-monitor-registry
          chart: public-endpoint-monitor
          targetRevision: "0.1.*"
        - repoURL: git@github.com:stokesy56/public-endpoint-monitor-gitops.git
          targetRevision: main

      helm:
        valueFiles:
          - apps/pem-{{env}}/values.yaml

      destination:
        server:    https://kubernetes.default.svc
        namespace: "{{ns}}"

      syncPolicy:
        automated:
          prune:    true
          selfHeal: true
